Fix ReadTheDocs generation by adding 'docs' dependency group to uv.lock
The docs dependency group was added to pyproject.toml in 3c185e7 but
uv.lock was not regenerated, causing ReadTheDocs builds to fail with:

  error: Group `docs` is not defined in the project's
         `dependency-groups` table

Signed-off-by: Jack Vreeken <jack@vreeken.me>